fin de sprint 1
WildCodeSchool/orleans-0917-beltoise pull request #2
Opened 2017-10-09 15:45 UTC by azurias

push de notre première semaine de travail !

2017-10-09 16:16 UTC, sblondeau requested changes

2017-10-09 16:16 UTC, sblondeau commented on public/accueil.php
> +        <div class="col-xs-12 col-md-offset-2 col-md-8">
col-xs-12 n'est pas nécessaire, par contre quel type d'affichage voulez vous en sm ? car la il fait du sm-12

2017-10-09 16:16 UTC, sblondeau commented on public/accueil.php
> +        <div class="col-xs-12 col-md-offset-1 col-md-10">
pareil pour les xs/sm (je ne le mets pas partout)

2017-10-09 16:16 UTC, sblondeau commented on public/footer.php
> +
footer vide ?

2017-10-09 16:16 UTC, sblondeau commented on public/footer.php
> +</div> <!-- // Close the container -->
il ferme quoi ce div ? le container est pas sur le section ?

2017-10-09 16:16 UTC, sblondeau commented on public/index.php
> +include 'renoveco.php';
va falloir revoir tout ça pour faire un petit MVC ;-)

2017-10-09 16:16 UTC, sblondeau commented on public/maconnerie.php
> +    </div>
ça sert à quoi ce div ? pour moi à rien car il n'y a rien dedans. Si tu veux faire un séparateur, à la rigueur c'est un hr qu'il te faut

2017-10-09 16:16 UTC, sblondeau commented on public/renoveco.php
> +        <div class="col-md-3">
attention à toutes ces parties écrites en "dur" qui seront au final à casser pour les rendre dynamique (récup depuis la bdd) du coup ne perdez pas trop de temsp pour l'instant sur leur mise en page, et passez le tout en dynamique au plus vite

2017-10-09 16:16 UTC, sblondeau commented on public/renoveco.php
> +    <div class="row realeco">
éviter de mettre des classes supplémentaires sur les div de row/container

2017-10-09 16:16 UTC, sblondeau commented on src/functions.php
> +function maPremiereFonction()
??? sert à quoi ? à rien je pense donc à supprimer :p

2017-10-10 07:31 UTC, TheophanyFR commented on public/accueil.php
> +        <div class="col-xs-12 col-md-offset-2 col-md-8">
corrigé

2017-10-10 07:38 UTC, TheophanyFR commented on public/accueil.php
> +        <div class="col-xs-12 col-md-offset-1 col-md-10">
corrigé

2017-10-10 07:45 UTC, TheophanyFR commented on public/footer.php
> +</div> <!-- // Close the container -->
Il ferme un container fluid situé à la fin de navbar qui wrap tout le site sauf la navbar (qui a son propre container fluid)

2017-10-10 07:50 UTC, TheophanyFR commented on src/functions.php
> +function maPremiereFonction()
supprimé

2017-10-10 10:25 UTC, TheophanyFR commented on public/renoveco.php
> +    <div class="row realeco">
corrigé

2017-10-11 13:28 UTC, closed without merging