Sprint 04 back delete slider certifs
WildCodeSchool/orleans-0917-beltoise pull request #29
Opened 2017-10-26 14:32 UTC by TheophanyFR

2017-10-27 07:41 UTC, sblondeau requested changes

2017-10-27 07:41 UTC, sblondeau commented on src/Controller/AdminController.php
> +            unlink('assets/uploads/' . $slide->getUri());
avant un unlink, c'est bien de vérifier que le fichier qu'on veut supprimer existe bel et bien (via un file_exists('monchemin/fichier')

2017-10-27 12:35 UTC, TheophanyFR commented
PR corrigée

2017-10-30 09:26 UTC, sblondeau requested changes

2017-10-30 09:26 UTC, sblondeau commented on src/Controller/AdminController.php
> +            if (file_exists('assets/uploads/' . $renovation->getImageBefore())
Attention ! deux fois before dans la condition

2017-10-30 09:28 UTC, TheophanyFR commented on src/Controller/AdminController.php
> +            if (file_exists('assets/uploads/' . $renovation->getImageBefore())
Oups, merci, corrigé !

2017-10-30 16:04 UTC, sblondeau approved these changes

2017-10-30 16:04 UTC, merged