Sprint 05 images fond
WildCodeSchool/orleans-0917-beltoise pull request #42
Opened 2017-11-03 14:36 UTC by Maxime-wcs

2017-11-03 15:34 UTC, sblondeau requested changes

2017-11-03 15:34 UTC, sblondeau commented on src/View/Admin/adminRealeco.html.twig
> +                <input type="file" name="upload">
et le label autour de "select image to upload" ?

2017-11-03 15:34 UTC, sblondeau commented on src/View/Admin/adminRenovations.html.twig
> +                Select image to upload:
pareil

2017-11-03 15:34 UTC, sblondeau commented on src/View/Admin/adminSlider.html.twig
> +                Select image to upload:
pareil

2017-11-03 16:37 UTC, Maxime-wcs commented
PR corrigée

2017-11-06 09:51 UTC, sblondeau requested changes

2017-11-06 09:51 UTC, sblondeau commented on src/View/Admin/adminPlatrerie.html.twig
> +                <label name="upload">Photo à modifier :</label>
le label doit avoir un attribut for relié à l'id du champ, ça ne va pas sinon... à remodif partout, et c'est bon, merci

2017-11-06 15:15 UTC, sblondeau approved these changes

2017-11-06 15:15 UTC, merged