Postprod modifclient
WildCodeSchool/orleans-0917-beltoise pull request #56
Opened 2017-11-26 10:47 UTC by TheophanyFR

2017-11-27 07:50 UTC, sblondeau requested changes

2017-11-27 07:50 UTC, sblondeau commented on public/assets/css/style.css
> +        background-color: #004741 !important;
pas de !important !!!!!

2017-11-27 17:12 UTC, TheophanyFR commented
correction effectuée

2017-11-28 14:07 UTC, open-it approved these changes

2017-11-28 14:07 UTC, merged