Sprint 02
WildCodeSchool/orleans-0917-beltoise pull request #6
Opened 2017-10-16 14:44 UTC by TheophanyFR

Dernière fois qu'on PR un gros paquet (no fake), maintenant l'architecture MVC est en place et pour les prochaines fois tu auras une PR par tâche :3

2017-10-17 22:35 UTC, sblondeau requested changes

2017-10-17 22:35 UTC, sblondeau commented on public/assets/css/style.css
> +#myCarousel img {
pas de css sur des id, que sur des classes, donc je ne veux pas voir de #

2017-10-17 22:35 UTC, sblondeau commented on public/assets/css/style.css
> +#footer-logo-beltoise {
pas de #

2017-10-17 22:35 UTC, sblondeau commented on src/Model/model.php
> +class model
un nom de fichier class et le nom de la classe doivent impérativement commencer par une majuscule !
de plus, une classe model est une entité qui represente quelque chose, l'appeler "model" n'a donc pas de sens

2017-10-17 22:35 UTC, sblondeau commented on src/View/Home/footer.html.twig
> +                <img src="http://via.placeholder.com/50x50" alt="qualibat"/>
de vrais images à mettre pour remplacer ces placeholder ?

2017-10-17 22:35 UTC, sblondeau commented on src/View/Home/footer.html.twig
> +        <!-- modale mentions legales -->
le fichier est long... par ex cette partie "mention légales" qui est bien distincte du reste du site pourrait etre crée dans un fichier séparé et appelé ici via un simple {% include 'mention_legales.html.twig' %}

2017-10-17 22:35 UTC, sblondeau commented on src/View/Home/maconnerie.html.twig
> +        <h2>Maçonnerie</h2>
le titre h2 ne devrait-il pas se trouver à l'intérieur des balises section juste dessous ?

2017-10-17 22:35 UTC, sblondeau commented on src/View/Home/platrerie.html.twig
> +        <h2>Plâtrerie</h2>
pareil pour le titre dans la section, je ne le répète pas à chaque fois si vous avez fait partout pareil

2017-10-18 07:30 UTC, azurias commented on src/Model/model.php
> +class model
La classe Model était uniquement la pour pouvoir uploader le dossier correspondant. Les users stories générant le modèle seront présentes sur le sprint de cette semaine.

2017-10-18 07:33 UTC, azurias commented on src/View/Home/footer.html.twig
> +                <img src="http://via.placeholder.com/50x50" alt="qualibat"/>
Non pas à ce stade, nous n'avons que la certification Qualibat qui apparaîtra dans le sprint 3.

2017-10-18 08:13 UTC, TheophanyFR commented
Changements effectués.

2017-10-20 07:56 UTC, sblondeau requested changes
pour les images de realisation, elles ne devraient pas etre versionnées !

2017-10-20 07:56 UTC, sblondeau commented on src/View/Home/platrerie.html.twig
> +                     style="height: 200px; width: 200px; ">
pas de style en inline !

2017-10-20 07:56 UTC, sblondeau commented on src/View/Home/platrerie.html.twig
> +                     style="height: 200px; width: 200px; ">
pas de style en inline

2017-10-20 07:56 UTC, sblondeau commented on src/View/Home/platrerie.html.twig
> +                     style="height: 200px; width: 200px; ">
je vous le remets pas partout mais y en a plein a modif

2017-10-20 08:45 UTC, sblondeau approved these changes

2017-10-20 08:46 UTC, merged